# Generated by Django 4.2.1 on 2023-06-04 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="Category",
            new_name="category",
        ),
    ]
